# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - bug
  - noteworthy
  - pull request submitted
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as 'stale' because no activity has 
  been detected in the last 90 days. The intent is to bring awareness to the 
  issue and to alert to the fact that the issue will be closed if no further 
  activity is detected within the next 14 days. If you are unable to make a 
  pull request for this issue, then please consider partnering with another 
  developer in the DNN community that is willing and able to assist. Thank 
  you for your continued contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed automatically due to the aforementioned detection 
  of activity. Feel free to re-open the issue if you believe it should not be 
  closed.
