//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class List_Country {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal List_Country() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.List_Country", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AC_Text {
            get {
                return ResourceManager.GetString("AC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AD_Text {
            get {
                return ResourceManager.GetString("AD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AE_Text {
            get {
                return ResourceManager.GetString("AE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AF_Text {
            get {
                return ResourceManager.GetString("AF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG_Text {
            get {
                return ResourceManager.GetString("AG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AI_Text {
            get {
                return ResourceManager.GetString("AI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AL_Text {
            get {
                return ResourceManager.GetString("AL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AM_Text {
            get {
                return ResourceManager.GetString("AM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AN_Text {
            get {
                return ResourceManager.GetString("AN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AO_Text {
            get {
                return ResourceManager.GetString("AO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AQ_Text {
            get {
                return ResourceManager.GetString("AQ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AR_Text {
            get {
                return ResourceManager.GetString("AR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AS_Text {
            get {
                return ResourceManager.GetString("AS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AT_Text {
            get {
                return ResourceManager.GetString("AT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AU_Text {
            get {
                return ResourceManager.GetString("AU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AW_Text {
            get {
                return ResourceManager.GetString("AW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AX_Text {
            get {
                return ResourceManager.GetString("AX.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AZ_Text {
            get {
                return ResourceManager.GetString("AZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BA_Text {
            get {
                return ResourceManager.GetString("BA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BB_Text {
            get {
                return ResourceManager.GetString("BB.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BD_Text {
            get {
                return ResourceManager.GetString("BD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BE_Text {
            get {
                return ResourceManager.GetString("BE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BF_Text {
            get {
                return ResourceManager.GetString("BF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BG_Text {
            get {
                return ResourceManager.GetString("BG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BH_Text {
            get {
                return ResourceManager.GetString("BH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BI_Text {
            get {
                return ResourceManager.GetString("BI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BJ_Text {
            get {
                return ResourceManager.GetString("BJ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BL_Text {
            get {
                return ResourceManager.GetString("BL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BM_Text {
            get {
                return ResourceManager.GetString("BM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BN_Text {
            get {
                return ResourceManager.GetString("BN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BO_Text {
            get {
                return ResourceManager.GetString("BO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BR_Text {
            get {
                return ResourceManager.GetString("BR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BS_Text {
            get {
                return ResourceManager.GetString("BS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BT_Text {
            get {
                return ResourceManager.GetString("BT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BV_Text {
            get {
                return ResourceManager.GetString("BV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BW_Text {
            get {
                return ResourceManager.GetString("BW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BY_Text {
            get {
                return ResourceManager.GetString("BY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BZ_Text {
            get {
                return ResourceManager.GetString("BZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CA_Text {
            get {
                return ResourceManager.GetString("CA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CC_Text {
            get {
                return ResourceManager.GetString("CC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CD_Text {
            get {
                return ResourceManager.GetString("CD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CF_Text {
            get {
                return ResourceManager.GetString("CF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CG_Text {
            get {
                return ResourceManager.GetString("CG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CH_Text {
            get {
                return ResourceManager.GetString("CH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CI_Text {
            get {
                return ResourceManager.GetString("CI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CK_Text {
            get {
                return ResourceManager.GetString("CK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CL_Text {
            get {
                return ResourceManager.GetString("CL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CM_Text {
            get {
                return ResourceManager.GetString("CM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CN_Text {
            get {
                return ResourceManager.GetString("CN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CO_Text {
            get {
                return ResourceManager.GetString("CO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CP_Text {
            get {
                return ResourceManager.GetString("CP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CR_Text {
            get {
                return ResourceManager.GetString("CR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CS_Text {
            get {
                return ResourceManager.GetString("CS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CU_Text {
            get {
                return ResourceManager.GetString("CU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CV_Text {
            get {
                return ResourceManager.GetString("CV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CX_Text {
            get {
                return ResourceManager.GetString("CX.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CY_Text {
            get {
                return ResourceManager.GetString("CY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CZ_Text {
            get {
                return ResourceManager.GetString("CZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DE_Text {
            get {
                return ResourceManager.GetString("DE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DG_Text {
            get {
                return ResourceManager.GetString("DG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DJ_Text {
            get {
                return ResourceManager.GetString("DJ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DK_Text {
            get {
                return ResourceManager.GetString("DK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DM_Text {
            get {
                return ResourceManager.GetString("DM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DO_Text {
            get {
                return ResourceManager.GetString("DO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DZ_Text {
            get {
                return ResourceManager.GetString("DZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EA_Text {
            get {
                return ResourceManager.GetString("EA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EC_Text {
            get {
                return ResourceManager.GetString("EC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EE_Text {
            get {
                return ResourceManager.GetString("EE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EG_Text {
            get {
                return ResourceManager.GetString("EG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EH_Text {
            get {
                return ResourceManager.GetString("EH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ER_Text {
            get {
                return ResourceManager.GetString("ER.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ES_Text {
            get {
                return ResourceManager.GetString("ES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ET_Text {
            get {
                return ResourceManager.GetString("ET.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EU_Text {
            get {
                return ResourceManager.GetString("EU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FI_Text {
            get {
                return ResourceManager.GetString("FI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FJ_Text {
            get {
                return ResourceManager.GetString("FJ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FK_Text {
            get {
                return ResourceManager.GetString("FK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FM_Text {
            get {
                return ResourceManager.GetString("FM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FO_Text {
            get {
                return ResourceManager.GetString("FO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FR_Text {
            get {
                return ResourceManager.GetString("FR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GA_Text {
            get {
                return ResourceManager.GetString("GA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GB_Text {
            get {
                return ResourceManager.GetString("GB.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GD_Text {
            get {
                return ResourceManager.GetString("GD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GE_Text {
            get {
                return ResourceManager.GetString("GE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GF_Text {
            get {
                return ResourceManager.GetString("GF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GG_Text {
            get {
                return ResourceManager.GetString("GG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GH_Text {
            get {
                return ResourceManager.GetString("GH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GI_Text {
            get {
                return ResourceManager.GetString("GI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GL_Text {
            get {
                return ResourceManager.GetString("GL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GM_Text {
            get {
                return ResourceManager.GetString("GM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GN_Text {
            get {
                return ResourceManager.GetString("GN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GP_Text {
            get {
                return ResourceManager.GetString("GP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GQ_Text {
            get {
                return ResourceManager.GetString("GQ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GR_Text {
            get {
                return ResourceManager.GetString("GR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GS_Text {
            get {
                return ResourceManager.GetString("GS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GT_Text {
            get {
                return ResourceManager.GetString("GT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GU_Text {
            get {
                return ResourceManager.GetString("GU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GW_Text {
            get {
                return ResourceManager.GetString("GW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GY_Text {
            get {
                return ResourceManager.GetString("GY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HK_Text {
            get {
                return ResourceManager.GetString("HK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HM_Text {
            get {
                return ResourceManager.GetString("HM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HN_Text {
            get {
                return ResourceManager.GetString("HN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HR_Text {
            get {
                return ResourceManager.GetString("HR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HT_Text {
            get {
                return ResourceManager.GetString("HT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HU_Text {
            get {
                return ResourceManager.GetString("HU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IC_Text {
            get {
                return ResourceManager.GetString("IC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ID_Text {
            get {
                return ResourceManager.GetString("ID.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IE_Text {
            get {
                return ResourceManager.GetString("IE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IL_Text {
            get {
                return ResourceManager.GetString("IL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IM_Text {
            get {
                return ResourceManager.GetString("IM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IN_Text {
            get {
                return ResourceManager.GetString("IN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IO_Text {
            get {
                return ResourceManager.GetString("IO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IQ_Text {
            get {
                return ResourceManager.GetString("IQ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IR_Text {
            get {
                return ResourceManager.GetString("IR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IS_Text {
            get {
                return ResourceManager.GetString("IS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IT_Text {
            get {
                return ResourceManager.GetString("IT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JE_Text {
            get {
                return ResourceManager.GetString("JE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JM_Text {
            get {
                return ResourceManager.GetString("JM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JO_Text {
            get {
                return ResourceManager.GetString("JO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JP_Text {
            get {
                return ResourceManager.GetString("JP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KE_Text {
            get {
                return ResourceManager.GetString("KE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KG_Text {
            get {
                return ResourceManager.GetString("KG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KH_Text {
            get {
                return ResourceManager.GetString("KH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KI_Text {
            get {
                return ResourceManager.GetString("KI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KM_Text {
            get {
                return ResourceManager.GetString("KM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KN_Text {
            get {
                return ResourceManager.GetString("KN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KP_Text {
            get {
                return ResourceManager.GetString("KP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KR_Text {
            get {
                return ResourceManager.GetString("KR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KW_Text {
            get {
                return ResourceManager.GetString("KW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KY_Text {
            get {
                return ResourceManager.GetString("KY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string KZ_Text {
            get {
                return ResourceManager.GetString("KZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LA_Text {
            get {
                return ResourceManager.GetString("LA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LB_Text {
            get {
                return ResourceManager.GetString("LB.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LC_Text {
            get {
                return ResourceManager.GetString("LC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LI_Text {
            get {
                return ResourceManager.GetString("LI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LK_Text {
            get {
                return ResourceManager.GetString("LK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LR_Text {
            get {
                return ResourceManager.GetString("LR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LS_Text {
            get {
                return ResourceManager.GetString("LS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LT_Text {
            get {
                return ResourceManager.GetString("LT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LU_Text {
            get {
                return ResourceManager.GetString("LU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LV_Text {
            get {
                return ResourceManager.GetString("LV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LY_Text {
            get {
                return ResourceManager.GetString("LY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MA_Text {
            get {
                return ResourceManager.GetString("MA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MC_Text {
            get {
                return ResourceManager.GetString("MC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MD_Text {
            get {
                return ResourceManager.GetString("MD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ME_Text {
            get {
                return ResourceManager.GetString("ME.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MF_Text {
            get {
                return ResourceManager.GetString("MF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MG_Text {
            get {
                return ResourceManager.GetString("MG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MH_Text {
            get {
                return ResourceManager.GetString("MH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MK_Text {
            get {
                return ResourceManager.GetString("MK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ML_Text {
            get {
                return ResourceManager.GetString("ML.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MM_Text {
            get {
                return ResourceManager.GetString("MM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MN_Text {
            get {
                return ResourceManager.GetString("MN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MO_Text {
            get {
                return ResourceManager.GetString("MO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MP_Text {
            get {
                return ResourceManager.GetString("MP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MQ_Text {
            get {
                return ResourceManager.GetString("MQ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MR_Text {
            get {
                return ResourceManager.GetString("MR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MS_Text {
            get {
                return ResourceManager.GetString("MS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MT_Text {
            get {
                return ResourceManager.GetString("MT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MU_Text {
            get {
                return ResourceManager.GetString("MU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MV_Text {
            get {
                return ResourceManager.GetString("MV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MW_Text {
            get {
                return ResourceManager.GetString("MW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MX_Text {
            get {
                return ResourceManager.GetString("MX.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MY_Text {
            get {
                return ResourceManager.GetString("MY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MZ_Text {
            get {
                return ResourceManager.GetString("MZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NA_Text {
            get {
                return ResourceManager.GetString("NA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NC_Text {
            get {
                return ResourceManager.GetString("NC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NE_Text {
            get {
                return ResourceManager.GetString("NE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NF_Text {
            get {
                return ResourceManager.GetString("NF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NG_Text {
            get {
                return ResourceManager.GetString("NG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NI_Text {
            get {
                return ResourceManager.GetString("NI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NL_Text {
            get {
                return ResourceManager.GetString("NL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NO_Text {
            get {
                return ResourceManager.GetString("NO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NP_Text {
            get {
                return ResourceManager.GetString("NP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NR_Text {
            get {
                return ResourceManager.GetString("NR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NU_Text {
            get {
                return ResourceManager.GetString("NU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NZ_Text {
            get {
                return ResourceManager.GetString("NZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OM_Text {
            get {
                return ResourceManager.GetString("OM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PA_Text {
            get {
                return ResourceManager.GetString("PA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PE_Text {
            get {
                return ResourceManager.GetString("PE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PF_Text {
            get {
                return ResourceManager.GetString("PF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PG_Text {
            get {
                return ResourceManager.GetString("PG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PH_Text {
            get {
                return ResourceManager.GetString("PH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PK_Text {
            get {
                return ResourceManager.GetString("PK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PL_Text {
            get {
                return ResourceManager.GetString("PL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PM_Text {
            get {
                return ResourceManager.GetString("PM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PN_Text {
            get {
                return ResourceManager.GetString("PN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PR_Text {
            get {
                return ResourceManager.GetString("PR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PS_Text {
            get {
                return ResourceManager.GetString("PS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PT_Text {
            get {
                return ResourceManager.GetString("PT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PW_Text {
            get {
                return ResourceManager.GetString("PW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PY_Text {
            get {
                return ResourceManager.GetString("PY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QA_Text {
            get {
                return ResourceManager.GetString("QA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QO_Text {
            get {
                return ResourceManager.GetString("QO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RE_Text {
            get {
                return ResourceManager.GetString("RE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RO_Text {
            get {
                return ResourceManager.GetString("RO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RS_Text {
            get {
                return ResourceManager.GetString("RS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RU_Text {
            get {
                return ResourceManager.GetString("RU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RW_Text {
            get {
                return ResourceManager.GetString("RW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SA_Text {
            get {
                return ResourceManager.GetString("SA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SB_Text {
            get {
                return ResourceManager.GetString("SB.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SC_Text {
            get {
                return ResourceManager.GetString("SC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SD_Text {
            get {
                return ResourceManager.GetString("SD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SE_Text {
            get {
                return ResourceManager.GetString("SE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SG_Text {
            get {
                return ResourceManager.GetString("SG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SH_Text {
            get {
                return ResourceManager.GetString("SH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SI_Text {
            get {
                return ResourceManager.GetString("SI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SJ_Text {
            get {
                return ResourceManager.GetString("SJ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SK_Text {
            get {
                return ResourceManager.GetString("SK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SL_Text {
            get {
                return ResourceManager.GetString("SL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SM_Text {
            get {
                return ResourceManager.GetString("SM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SN_Text {
            get {
                return ResourceManager.GetString("SN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SO_Text {
            get {
                return ResourceManager.GetString("SO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SR_Text {
            get {
                return ResourceManager.GetString("SR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ST_Text {
            get {
                return ResourceManager.GetString("ST.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SV_Text {
            get {
                return ResourceManager.GetString("SV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SY_Text {
            get {
                return ResourceManager.GetString("SY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SZ_Text {
            get {
                return ResourceManager.GetString("SZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TA_Text {
            get {
                return ResourceManager.GetString("TA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TC_Text {
            get {
                return ResourceManager.GetString("TC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TD_Text {
            get {
                return ResourceManager.GetString("TD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TF_Text {
            get {
                return ResourceManager.GetString("TF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TG_Text {
            get {
                return ResourceManager.GetString("TG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TH_Text {
            get {
                return ResourceManager.GetString("TH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TJ_Text {
            get {
                return ResourceManager.GetString("TJ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TK_Text {
            get {
                return ResourceManager.GetString("TK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TL_Text {
            get {
                return ResourceManager.GetString("TL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TM_Text {
            get {
                return ResourceManager.GetString("TM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TN_Text {
            get {
                return ResourceManager.GetString("TN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TO_Text {
            get {
                return ResourceManager.GetString("TO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TR_Text {
            get {
                return ResourceManager.GetString("TR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TT_Text {
            get {
                return ResourceManager.GetString("TT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TV_Text {
            get {
                return ResourceManager.GetString("TV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TW_Text {
            get {
                return ResourceManager.GetString("TW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TZ_Text {
            get {
                return ResourceManager.GetString("TZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UA_Text {
            get {
                return ResourceManager.GetString("UA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UG_Text {
            get {
                return ResourceManager.GetString("UG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UM_Text {
            get {
                return ResourceManager.GetString("UM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string US_Text {
            get {
                return ResourceManager.GetString("US.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UY_Text {
            get {
                return ResourceManager.GetString("UY.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UZ_Text {
            get {
                return ResourceManager.GetString("UZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VA_Text {
            get {
                return ResourceManager.GetString("VA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VC_Text {
            get {
                return ResourceManager.GetString("VC.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VE_Text {
            get {
                return ResourceManager.GetString("VE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VG_Text {
            get {
                return ResourceManager.GetString("VG.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VI_Text {
            get {
                return ResourceManager.GetString("VI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VN_Text {
            get {
                return ResourceManager.GetString("VN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VU_Text {
            get {
                return ResourceManager.GetString("VU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WF_Text {
            get {
                return ResourceManager.GetString("WF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WS_Text {
            get {
                return ResourceManager.GetString("WS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string YE_Text {
            get {
                return ResourceManager.GetString("YE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string YT_Text {
            get {
                return ResourceManager.GetString("YT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ZA_Text {
            get {
                return ResourceManager.GetString("ZA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ZM_Text {
            get {
                return ResourceManager.GetString("ZM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ZW_Text {
            get {
                return ResourceManager.GetString("ZW.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ZZ_Text {
            get {
                return ResourceManager.GetString("ZZ.Text", resourceCulture);
            }
        }
    }
}
